version: '3.6'

services:
  consul1:
    image: consul:latest
    container_name: consul1
    restart: always
    network_mode: host
    command: agent -server -bootstrap -ui -bind=192.168.1.100 -client=0.0.0.0
    volumes:
      - ./data/consul:/consul/data
      - /etc/localtime:/etc/localtime:ro